#%RAML 0.8
title: marketing
version: 1

#baseUri: https://economistapi.cloudhub.io/marketing/
baseUri: http://mocksvc.mulesoft.com/mocks/132b6108-a362-49e5-bd48-dfbc95d33e98/marketing/

/:
  description: root endpoint
  get:
    displayName: Root
/version:
  description: build information endpoint.
  get:
    displayName: Version
/partner:
  description: |
    Represents all of the partners known by The Economist.
  get:
    description: |
      Retrieve all known partners.
    displayName: Partners
    responses:
      200:
        description: |
          Successfully retrieved partners
        body:
          application/json:
            example: |
              "partners": [
                {
                  "id": "ISIC",
                  "location": "{baseUri}/partners/ISIC",
                }
                {
                  "user_account": "EthiopianAirlines",
                  "location": "{baseUri}/partners/EthiopianAirlines",
                }
              ]
  /{number}:
    description: Represents a partnemr membership number
    get:
      description: Validate the membership number
      displayName: Validate
      responses:
        200:
          description: The membership number is valid
          body:
            application/json:
              example: |
                {
                  "number": "00012000015",
                  "location": "{baseuri}/partners/EthiopianAirlines/00012000015"
                }
        400:
          description: The membership number is invalid
          body:
            application/json:
              example: |
                {
                  "number": "00012000016",
                  "error": "Invalid check digit"
                }